use arrow::array::{Int64Array, StringArray};
use datafusion::prelude::*;
use proptest::prelude::*;
use tempfile::tempdir;

use mesodb_core::config::Config;
use mesodb_core::datom::Datom;
use mesodb_core::memtable::MemTable;
use mesodb_core::schema::{SchemaMap, ValueType};
use mesodb_core::storage::BackgroundCompactor;
use mesodb_core::transactor::{Fact, Transactor};
use mesodb_core::types::Value;

// =====================================================================
// VECTOR 1: TEMPORAL COLLISION SUITE
// =====================================================================

#[tokio::test]
async fn test_temporal_zero_length_interval() {
    let dir = tempdir().unwrap();
    let compactor = BackgroundCompactor::new(dir.path().to_path_buf());
    let mut mt = MemTable::new(10);

    let e = 1;
    let a = 10;
    let collision_time = 1000;

    // 1. Transaction 1: Assert a value
    mt.append(Datom::assert(e, a, Value::Int64(99), 1, collision_time));

    // 2. Transaction 2: Retract it in the EXACT SAME microsecond
    mt.append(Datom::retract(e, a, Value::Int64(99), 2, collision_time));

    let batch = mt.finish().unwrap();
    let path = compactor.flush_to_parquet(batch, 1).unwrap();

    // 3. Force Option A Compaction
    let compacted_path = compactor.compact(&[path], 2).await.unwrap();

    // 4. Validate DataFusion's boundary math survives the collision
    let ctx = SessionContext::new();
    ctx.register_parquet(
        "compacted",
        compacted_path.to_str().unwrap(),
        Default::default(),
    )
    .await
    .unwrap();

    let df = ctx
        .sql("SELECT valid_from, valid_to FROM compacted")
        .await
        .unwrap();
    let results = df.collect().await.unwrap();

    let result_batch = &results[0];

    // The retraction row must be purged, leaving only the assertion.
    assert_eq!(
        result_batch.num_rows(),
        1,
        "Zero-length interval must yield exactly 1 reified row."
    );

    let from_col =
        arrow::compute::cast(result_batch.column(0), &arrow::datatypes::DataType::Int64).unwrap();
    let to_col =
        arrow::compute::cast(result_batch.column(1), &arrow::datatypes::DataType::Int64).unwrap();
    let from_arr = from_col.as_any().downcast_ref::<Int64Array>().unwrap();
    let to_arr = to_col.as_any().downcast_ref::<Int64Array>().unwrap();

    // The LEAD() window function must successfully bind both valid_from and valid_to to the same timestamp.
    assert_eq!(from_arr.value(0), collision_time);
    assert_eq!(
        to_arr.value(0),
        collision_time,
        "The interval must gracefully close itself at length zero."
    );
}

#[tokio::test]
async fn test_deep_retroactive_retrofitting() {
    let dir = tempdir().unwrap();
    let mut schema = SchemaMap::new();
    schema.add_attribute(":sys/status", ValueType::String, false);

    let mut t = Transactor::new(dir.path().join("wal.db"), schema, Config::default()).unwrap();

    // 1. Assert Current State (T = 5000)
    t.transact_at(
        vec![Fact {
            e: 1,
            ident: ":sys/status".into(),
            v: Value::String("Active".into()),
            op: true,
            cas_old_v: None,
            valid_time: None,
        }],
        5000,
    )
    .unwrap();

    // 2. Retroactively insert past state (T = 1000)
    // This physically occurs at Tx 2, but logically occurs deep in the past.
    t.transact_at(
        vec![Fact {
            e: 1,
            ident: ":sys/status".into(),
            v: Value::String("Pending".into()),
            op: true,
            cas_old_v: None,
            valid_time: None,
        }],
        1000,
    )
    .unwrap();

    // Reconstruct the raw batches generated by the transactor to feed the compactor
    let batches: Vec<_> = (1..=2)
        .map(|tx| {
            let mut mt = MemTable::new(10);
            // We simulate reading the Transactor's raw output by manually reconstructing the known datoms
            if tx == 1 {
                mt.append(Datom::assert(
                    1,
                    100,
                    Value::String("Active".into()),
                    1,
                    5000,
                ));
            } else {
                mt.append(Datom::assert(
                    1,
                    100,
                    Value::String("Pending".into()),
                    2,
                    1000,
                ));
            }
            mt.finish().unwrap()
        })
        .collect();

    let compactor = BackgroundCompactor::new(dir.path().to_path_buf());
    let p1 = compactor.flush_to_parquet(batches[0].clone(), 1).unwrap();
    let p2 = compactor.flush_to_parquet(batches[1].clone(), 2).unwrap();

    let compacted_path = compactor.compact(&[p1, p2], 3).await.unwrap();

    let ctx = SessionContext::new();
    ctx.register_parquet(
        "compacted",
        compacted_path.to_str().unwrap(),
        Default::default(),
    )
    .await
    .unwrap();

    // Query sorted logically by valid_time
    let df = ctx
        .sql("SELECT v_str, valid_from, valid_to FROM compacted ORDER BY valid_from ASC")
        .await
        .unwrap();
    let results = df.collect().await.unwrap();
    let batch = &results[0];

    assert_eq!(
        batch.num_rows(),
        2,
        "Retroactive split must result in two distinct intervals"
    );

    let val_arr = arrow::compute::cast(batch.column(0), &arrow::datatypes::DataType::Utf8).unwrap();
    let from_arr =
        arrow::compute::cast(batch.column(1), &arrow::datatypes::DataType::Int64).unwrap();
    let to_arr = arrow::compute::cast(batch.column(2), &arrow::datatypes::DataType::Int64).unwrap();

    let v = val_arr.as_any().downcast_ref::<StringArray>().unwrap();
    let f = from_arr.as_any().downcast_ref::<Int64Array>().unwrap();
    let to = to_arr.as_any().downcast_ref::<Int64Array>().unwrap();

    // Interval 1: Pending [1000, 5000)
    assert_eq!(v.value(0), "Pending");
    assert_eq!(f.value(0), 1000);
    assert_eq!(to.value(0), 5000);

    // Interval 2: Active [5000, i64::MAX)
    assert_eq!(v.value(1), "Active");
    assert_eq!(f.value(1), 5000);
    assert_eq!(to.value(1), i64::MAX);
}

#[tokio::test]
async fn test_multi_interval_gap_completion() {
    let dir = tempdir().unwrap();
    let compactor = BackgroundCompactor::new(dir.path().to_path_buf());
    let mut mt = MemTable::new(10);

    let e = 99;
    let a = 50;

    // Block 1: [1000, 2000)
    mt.append(Datom::assert(e, a, Value::Int64(1), 1, 1000));
    mt.append(Datom::retract(e, a, Value::Int64(1), 2, 2000));

    // Block 2: [4000, 5000)
    mt.append(Datom::assert(e, a, Value::Int64(3), 3, 4000));
    mt.append(Datom::retract(e, a, Value::Int64(3), 4, 5000));

    // The Stitch: [2000, 4000) -> Fits perfectly in the historical gap
    mt.append(Datom::assert(e, a, Value::Int64(2), 5, 2000));
    mt.append(Datom::retract(e, a, Value::Int64(2), 6, 4000));

    let batch = mt.finish().unwrap();
    let path = compactor.flush_to_parquet(batch, 1).unwrap();
    let compacted_path = compactor.compact(&[path], 2).await.unwrap();

    let ctx = SessionContext::new();
    ctx.register_parquet(
        "compacted",
        compacted_path.to_str().unwrap(),
        Default::default(),
    )
    .await
    .unwrap();

    let df = ctx
        .sql("SELECT v_int, valid_from, valid_to FROM compacted ORDER BY valid_from ASC")
        .await
        .unwrap();
    let results = df.collect().await.unwrap();
    let batch = &results[0];

    assert_eq!(
        batch.num_rows(),
        3,
        "Engine must stitch the 3 segments without overlaps or dropped rows."
    );

    let v_col = arrow::compute::cast(batch.column(0), &arrow::datatypes::DataType::Int64).unwrap();
    let v_arr = v_col.as_any().downcast_ref::<Int64Array>().unwrap();

    // Verify perfect continuous continuity
    assert_eq!(v_arr.value(0), 1); // 1000-2000
    assert_eq!(v_arr.value(1), 2); // 2000-4000
    assert_eq!(v_arr.value(2), 3); // 4000-5000
}

// =====================================================================
// PROPERTY-BASED FUZZING (PROPTEST)
// =====================================================================

proptest! {
    #[test]
    fn proptest_randomized_temporal_collisions(
        t1 in 0i64..5000,
        t2 in 0i64..5000,
        t3 in 0i64..5000,
    ) {
        // Execute an async block synchronously for proptest
        tokio::runtime::Runtime::new().unwrap().block_on(async {
            let dir = tempdir().unwrap();
            let compactor = BackgroundCompactor::new(dir.path().to_path_buf());
            let mut mt = MemTable::new(10);
            let e = 42;
            let a = 10;

            // Generate chaotic assertions and retractions
            mt.append(Datom::assert(e, a, Value::Int64(10), 1, t1));
            mt.append(Datom::retract(e, a, Value::Int64(10), 2, t2));
            mt.append(Datom::assert(e, a, Value::Int64(20), 3, t3));

            let batch = mt.finish().unwrap();
            let path = compactor.flush_to_parquet(batch, 1).unwrap();

            // The goal of this test is crash resistance. DataFusion's LEAD() function
            // and the Parquet flush mechanism must NEVER panic under boundary chaos.
            let result = compactor.compact(&[path], 2).await;

            assert!(result.is_ok(), "Compaction panicked under randomized temporal fuzzing");
        });
    }
}
