# mesodb-server/Cargo.toml

[package]
name = "mesodb-server"
description.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mesodb-core.workspace = true

arrow.workspace = true
arrow-flight.workspace = true
axum.workspace = true
color-eyre.workspace = true
futures.workspace = true
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemallocator = "0.7.0"

[dev-dependencies]
tempfile.workspace = true
