[workspace]
resolver = "2"
members = [
    "mesodb-bench",
    "mesodb-core",
    "mesodb-server",
    "mesodb-cli"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["yeajustmars"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
mesodb-core = { path = "mesodb-core", version = "0.1.0" }

# Config
toml = "1.1.2+spec-1.1.0"

# Data, Engine & Storage
arrow = "58.2.0"
ahash = "0.8.12"
chrono = "0.4.44"
lru = "0.18.0"
ordered-float = "5.3.0"
parquet = "58.2.0"
rkyv = "0.8.16"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

# Parsing & Query
datafusion = "53.1.0"
pest = "2.8.6"
pest_derive = "2.8.6"

# Async & Web
tokio = { version = "1.52.2", features = ["full"] }
axum = "0.8.9"

# Observability & Errors
thiserror = "2.0.18"
color-eyre = "0.6.5"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

# CLI
# TODO: replace with clap
rustyline = "14.0.0" # TODO: update to most recent version
comfy-table = "7.1.1" # TODO: update to most recent version

# Testing, dev, misc.
tempfile = "3.27.0"
