[workspace]
resolver = "2"
members = [
    "mesodb-bench",
    "mesodb-doc",
    "mesodb-core",
    "mesodb-server",
    "mesodb-cli"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["yeajustmars"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
mesodb-core = { path = "mesodb-core", version = "0.1.0" }
mesodb-server = { path = "mesodb-server", version = "0.1.0" }

# Core system (core, server, CLI, ...)
arrow = "58.2.0"
arrow-flight = "58.2.0"
ahash = "0.8.12"
axum = { version = "0.8.9", features = ["json", "macros"] }
chrono = "0.4.44"
clap = { version = "4.6.1", features = ["derive"] }
color-eyre = "0.6.5"
comfy-table = "7.2.2"
datafusion = "53.1.0"
futures = "0.3.32"
ordered-float = "5.3.0"
parking_lot = "0.12.5"
parquet = "58.2.0"
pest = "2.8.6"
pest_derive = "2.8.6"
prost = "0.14.4"
reedline = "0.38.0"
reqwest = { version = "0.13.3", features = ["json"] }
rkyv = "0.8.16"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.52.2", features = ["full"] }
tokio-stream = "0.1.18"
toml = "1.1.2"
tonic = "0.14.6"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

# Docs
mdcat = "2.12.0"
pulldown-cmark = "0.12"
pulldown-cmark-mdcat = "2.12.0"
rust-embed = "8.12.0"
syntect = "5.3.0"

# Testing, dev, misc.
tempfile = "3.27.0"
