// mesodb-core/src/datalog.pest

WHITESPACE = _{ " " | "\t" | "\r" | "\n" | "," }

// --- Primitives ---
ident    = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_" | "-")* }
variable = @{ "?" ~ ident }
keyword  = @{ ":" ~ ident ~ ("/" ~ ident)? }
blank    = { "_" }
boolean  = { "true" | "false" }
data_src = { "$" | "%" }

float    = @{ "-"? ~ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT+ }
integer  = @{ "-"? ~ ASCII_DIGIT+ }

inner    = @{ (!"\"" ~ ANY)* }
string   = ${ "\"" ~ inner ~ "\"" }

term = { blank | boolean | variable | keyword | string | float | integer | data_src }

// --- Find Clause ---
wildcard     = { "*" }
pull_attr    = { wildcard | pull_map | keyword }
pull_map     = { "{" ~ keyword ~ pull_pattern ~ "}" }
pull_pattern = { "[" ~ pull_attr+ ~ "]" }
pull_expr    = { "(" ~ "pull" ~ variable ~ pull_pattern ~ ")" }
aggr_expr    = { "(" ~ ident ~ variable ~ ")" }

find_elem    = { pull_expr | aggr_expr | variable }
find_clause  = { ":find" ~ find_elem+ }

// --- In Clause ---
in_elem      = { data_src | variable }
in_clause    = { ":in" ~ in_elem+ }

// --- Where Clause ---
data_pattern   = { "[" ~ term ~ term ~ term? ~ term? ~ term? ~ "]" }
rule_expr      = { "(" ~ ident ~ term+ ~ ")" }
operator       = { "<=" | ">=" | "!=" | "<" | ">" | "=" | "+" | "-" | "*" | "/" | ident }
fn_expr        = { "(" ~ operator ~ term+ ~ ")" }
binding_rel    = { "[[" ~ variable+ ~ "]]" }
binding_tuple  = { "[" ~ variable+ ~ "]" }
binding_scalar = { variable }
binding        = { binding_rel | binding_tuple | binding_scalar }
fn_clause      = { "[" ~ fn_expr ~ binding? ~ "]" }

// --- Logic Branching ---
join_vars    = { "[" ~ variable+ ~ "]" }
or_clause    = { "(" ~ ("or-join" | "or") ~ join_vars? ~ where_elem+ ~ ")" }
not_clause   = { "(" ~ ("not-join" | "not") ~ join_vars? ~ where_elem+ ~ ")" }
where_elem   = { fn_clause | data_pattern | rule_expr | or_clause | not_clause }
where_clause = { ":where" ~ where_elem+ }

// --- Rules ---
rule_head    = { "(" ~ ident ~ variable+ ~ ")" }
rule_def     = { "[" ~ rule_head ~ where_elem+ ~ "]" }
ruleset      = { SOI ~ "[" ~ rule_def+ ~ "]" ~ EOI }

// --- Root ---
query        = { SOI ~ "[" ~ find_clause ~ in_clause? ~ where_clause ~ "]" ~ EOI }
