[package]
name = "mesodb-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mesodb-core.workspace = true
tokio.workspace = true
color-eyre.workspace = true

# TODO: look if we need these after basic test
rustyline.workspace = true
comfy-table.workspace = true
datafusion.workspace = true
