# mesodb-cli/Cargo.toml
[package]
name = "mesodb-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
comfy-table.workspace = true
crossterm.workspace = true
nu-ansi-term.workspace = true
ratatui.workspace = true
reedline.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full", "macros"] }

mesodb-core = { path = "../mesodb-core" }
mesodb-doc = { path = "../mesodb-doc" }
