[package]
name = "mesodb-core"
description.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ahash.workspace = true
arrow.workspace = true
bytemuck.workspace = true
chrono.workspace = true
datafusion.workspace = true
memmap2.workspace = true
ordered-float.workspace = true
parking_lot.workspace = true
parquet.workspace = true
pest.workspace = true
pest_derive.workspace = true
rkyv.workspace = true
roaring.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
