[package]
name = "mesodb-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ahash.workspace = true
arrow.workspace = true
chrono.workspace = true
datafusion.workspace = true
ordered-float.workspace = true
parquet.workspace = true
pest.workspace = true
pest_derive.workspace = true
rkyv.workspace = true
serde.workspace = true
tokio.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
