[package]
name = "mesodb-bench"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ahash.workspace = true
arrow.workspace = true
datafusion.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["full"] }

mesodb-core = { path = "../mesodb-core" }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["async_tokio"] }
proptest = "1.11.0"

[[bench]]
name = "ingestion"
harness = false

[[bench]]
name = "query"
harness = false

[[bench]]
name = "velocity_sentinel"
harness = false
