[package]
name = "mesodb-bench"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dev-dependencies]
mesodb-core = { path = "../mesodb-core" }

criterion = { version = "0.8.2", features = ["async_tokio"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["full"] }

[[bench]]
name = "ingestion"
harness = false

[[bench]]
name = "query"
harness = false
